[build]
  publish = "/"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "chrome-aws-lambda", "puppeteer-core"]

[functions.scrapeData]
  timeout = 30
