[build]
  publish = "/"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio"]

[functions.scrapeData]
  timeout = 20
